### ISSUE TITLE
Add support for discarding version concurrency check instead of throwing an exception

### ISSUE THREAD

**Issue by RyanElfman** [Eveneum/Eveneum#10]
I've been playing around with Evenenum for a little while and have been enjoying it so far although I've ran into a problem. I'm testing the throughput of my application by simply executing 1000 calls (just a simple for loop) to my server which does the following: 

1. Loads the aggregate from Eveneum by calling ReadStreamFromVersion with the expected version of 0.
2. Perform functionality against the aggregate (in this case it's adding an account)
3. Save the aggregate back through Eveneum.

It's really simple solution but the performance is really bad and I run into the OpimisticConcurrencyException 50% of the time. I tried the documented way of catching the exception and re-trying but in a high throughput scenario I keep running into the concurrency issue.

Is there a way to ignore the Version and just write the event? Also, is there an example of using Eveneum in a high-performance way? Should I be storing the last snapshot version in memory and only ReadStreamFromVersion with that version? 

Some guidance would be greatly appreciated

**Comment by jkonecki** [comment]
Hello Ryan,

Thank you for your feedback!

Are you using the same aggregate, and therefore loading the same stream, in
all the calls?

**Comment by RyanElfman** [comment]
Correct, this is all using a single aggregate. Here's my code used to interact with Eveneum:

```
public async Task<(object? Snapshot, AggregateEvent[]? Events)>
	LoadEvents(string streamId, ulong version, CancellationToken cancellationToken = default)
{
	var response = await _eventStore.ReadStream(streamId, cancellationToken).ConfigureAwait(false);

	(object? Snapshot, AggregateEvent[]? Events) ret = default;

	ret.Snapshot = response?.Stream?.Snapshot?.Data;

	var events = response?.Stream?.Events;
	if (events?.LongLength > 0)
	{
		var aggregateEvents = new AggregateEvent[events.LongLength];
		for (long i = 0; i < aggregateEvents.LongLength; i++)
		{
			EventData e = events[i];
			aggregateEvents[i] = (AggregateEvent)e.Body;
			aggregateEvents[i].Version = e.Version;
		}

		ret.Events = aggregateEvents;
	}

	return ret;
}

public async Task SaveEvents(string streamId, ulong expectedVersion,
	IReadOnlyList<AggregateEvent> events, CancellationToken cancellationToken = default)
{
	ulong? expected = null;
	if (expectedVersion > 0)
		expected = expectedVersion;

	ArrayPool<EventData> pool = ArrayPool<EventData>.Shared;
	EventData[] data = pool.Rent(events.Count);

	try
	{
		for (int i = 0; i < events.Count; i++)
			data[i] = new EventData(streamId, events[i], null, events[i].Version);

		await _eventStore.WriteToStream(streamId, data[0..events.Count], expected, null, cancellationToken).ConfigureAwait(false);
	}
	finally
	{
		pool.Return(data);
	}
}
```
As you may notice I switched to using ReadStream() instead of ReadStreamFromVersion() to be able to get the snapshots. This improves it slightly but the concurrency issue is still there. 

My client that I'm testing this with is on the browser, this is where I hammer these 2 functions.

**Comment by jkonecki** [comment]
What you observe is actually the desired behaviour. Let me explain in more detail:

When new events are appended to the stream, you need to know which versions they have. In Event Sourcing, the order of events in the stream is guaranteed and you cannot have multiple events with the same version. In my experience in most cases the order of events in the stream matters. Even if you take as an example credit and debit events in bank account history: one may think that the order doesn't really matter, they would sum to the same final balance after all, but there are side-effects - the order would affect if the account was overdrawn or not.

The concurrency exception you are getting is the result of running two instances of the same aggregate in parallel. For get for a moment about event sourcing and assume the state is stored in a relational database. What would you do? Would you still update the record in a table knowing that the other process modified it in the meantime? Does your current update even make sense now? Do you really want to lose the update made by other process? What about all the processing done by the other process that was completed with the assumption that the update was successful?

There are a few ways to 'solve' that problem:

1. Leave it as it is
If your aggregate design is are desired then catch concurrency exception and retry. If you have a long stream use snapshots to minimize the about of data read from CosmosDB

2. Use single aggregate instance
Instead of running multiple instances of the aggregate, use only a single instance - that removes the problem completely. If you keep that aggregate in memory, you will get a huge perf improvement as well, as you will read the stream only once, and then only append new events (you're probably more than halving required RU/s).
This is relatively easy to do on a single machine, but if you want scale that you're into distributed systems territory and picking up an actor framework like Microsoft Orleans or Akka.net should be preferred to rolling out own solution.

3. Redesign the aggregate
Consider breaking the aggregate into smaller ones - there will be fewer chances of concurrency issues. For example, instead of having one, big Player aggregate, consider having separate ones for storing player details, managing game sessions, keeping inventory, tracking scores, etc.

If you're just doing a performance test by hammering a single aggregate / stream, than I would argue this is not a test that represents real usage. You increase your throughput by using multiple aggregates at the same time, and therefore fully utilizing your provisioned RU/s for all physical partitions.
