### ISSUE TITLE
Consider using typed bodies

### ISSUE THREAD

**Issue by MPapst** [Eveneum/Eveneum#4]
Hi,

I found your library and think I would like to use it in one of my projects.
Have you considered using typed Bodies using C# generics?

This would change from using object types to strongly typed results.

Would it be okay for you if I try to implement this as a contribution?

**Comment by jkonecki** [comment]
Hi Marco,

I would like to know more about your planned usage.

At the moment the actual body object deserialised is of the concrete type
that was passed to the WriteToStream method.
Since the stream will usually contain events of many different type, each
EventData object would have to be of potentially different type, is.
EventData<EventTypeA>, EventData<EventTypeB>, etc. When reading a stream
you don't know upfront which event is of which type, and you need a
collection that can contain all EventData<T> instances.
You cannot load all events into a strongly typed collection, like
List<EventData<EventTypeA>>.

I always found that I need a dynamic dispatch functionality to apply events
to my aggregates anyway, so I didn't need generic EventData.

Please let me know what is your requirement for generic EventData and I'm
happy to consider incorporating it. Let me know if you would like to
discuss the ways of using Eveneum in your project.

**Comment by MPapst** [comment]
Hi Jakub,

wherever I find boxing a class into the object type, it brings up possible type errors which need to be handled. To work more type-safe I would like to use strongly typed object wherever it is possible.

As far as I understood (please correct me if I am wrong) event stores, you know at least per stream (which represents the history of one special entity) what kind of object is expected.

Bringing exact types in here brings up some issues especially when versioning entities. (e.g. removing or adding properties - but you always have that later in your application since c# is typed anyway.

The idea would be having the typing optional. This would result in kind of breaking change as the EventData would be necessarily changed from **struct to class**.
I would introduce it like this:
```csharp
public class EventData<TBody, TMetada>
{
        public string StreamId {get; }
        public TBody Body {get;}
        public TMetaData Metadata{get;}
        public ulong Version{get;}

        public EventData(string streamId, TBody body, TMetaData metadata, ulong version)
        {
            this.StreamId = streamId;
            this.Body = body;
            this.Metadata = metadata;
            this.Version = version;
        }
}
```
(I haven't digged enough to say right now if it works with the properties like this)
and a compatability layer:
```csharp
public class EventData : EventData<object, object> {}
```

This would allow to have both, depending on the needs of the current application or the application state. This would even allow to write strongly typed and read object type (I am not sure about a scenario for that requirement, but it would work).

**Comment by jkonecki** [comment]
I get what you're saying, but the real question is: what type of the
collection of events would you like? And what code would you like to write
to process all different types of events and take advantage of the strongly
typed Body property?

Remember that each event in the stream can have a different type.

**Comment by MPapst** [comment]
sorry, that I did not reply directly.
You are right, there is no scenario where this would work. I think this was a misunderstanding of mine of the Event Sourcing pattern, thinking of that it is a kind of memento instead of update events that are stored in the stream.
