### ISSUE TITLE
Reply stream

### ISSUE THREAD

**Issue by ekjuanrejon** [Eveneum/Eveneum#6]
How can a stream be replayed?
Do you use cosmos change feed?

**Comment by wtt235-bh** [comment]
I think this would be supported, given that event documents are partitioned by stream ID - meaning event ordering in the change feed would be preserved. 

One thing that would be nice is if you could split the snapshot and event documents into separate cosmos containers.  The main advantage would be a change feed that would only contain event appends, and not changes to a snapshot.  It would appear that today you would need to filter out changes to the snapshot from the events.  You’d probably still need to filter out changes to the stream header document, but at least at this point that would be a smaller set of changes to filter out.  A nice added benefit of separating the containers would be the ability to manage RUs for reading and writing independently. 

With the introduction of the change feed processor in V3 of the cosmos client, it might be nice to include an “Event Processor” library as part of Eveneum that filtered out things you might not want (and maybe the ability to customize and extend that filtering).

**Comment by Aakoo76** [comment]
Replay is basically a ReadStream -call. You will get all events from beginning or latest snapshot.

I use cosmos change feed in my prototype project. It is doable, but I find it a bit cumbersome with Eveneum, since a Eveneum document is stored to Cosmos, but the library declares EveneumDocument private/internal to it self. So, I need to redeclare similar class on my change feed Azure function. Would be fairly much easier if the EveneumDocument was public, then could deserialize the comsos document into EveneumDocument and not need to handle deserialization of the event my self. Perhaps there is a better way, but I haven't realized one yet.

**Comment by jkonecki** [comment]
Sorry for a late reply, didn't get a notification from GitHub.

Ari is correct, replaying a stream involves reading it and processing all the events / snapshot again.

I understand your point regarding event deserialization when using Change Feed. Would the following feature help:

Eveneum would expose a `Serializer` class that would take documents returned from Change Feed and deserialize them to `EventData` or `Snapshot` objects. I don't think we need to make `EveneumDocument` public - as long as I can deserialize the raw document from Change Feed.

Do you guys use ChangeFeedProcessor or SQL API?

**Comment by Aakoo76** [comment]
> Sorry for a late reply, didn't get a notification from GitHub.

> Eveneum would expose a `Serializer` class that would take documents returned from Change Feed and deserialize them to `EventData` or `Snapshot` objects. I don't think we need to make `EveneumDocument` public - as long as I can deserialize the raw document from Change Feed.

Yes, this sounds good to me! As long as there is a way to get IReadOnlyList<Document> without further hassle to EventData, I am fine. I actually did already my implementation, but I thinnk this is something that should be done in the library.

> Do you guys use ChangeFeedProcessor or SQL API?

I use Azure functions, where I get list of IReadOnlyList<Document> as an argument, when collection has a change.

-- ARi

**Comment by jkonecki** [comment]
@ekjuanrejon Eveneum doesn't support projections as GetEventStore does.

You can retrieve certain events from multiple streams by using `IAdvancedEventStore.LoadEvents` method - the first parameter is a CosmosDB SQL query. The example of the query:

`SELECT * FROM c WHERE startswith(c.BodyType, 'MyEventType')`

The second parameter is a callback which will be invoked by Eveneum for each page of results.

Please let me know if you need more guidance.

The 'proper' solution for projections would be to subscribe to ChangeFeed. However, there is a limitation in Change Feed processor as CosmosDB doesn't support any filtering in change feed. You will have to read all documents and filter out the events you're interested in manually. There is an outstanding [UserVoice](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/20244082-support-filters-queries-on-the-change-feed), you are welcomed to vote on it.

**Comment by ThomasVandenbon** [comment]
@jkonecki I think it would be very helpful to have some documentation on how Projections could be tackled using Eveneum. I personally believe that this is currently the hardest part.

Especially in regards to how to keep streams up to date after they've been brought up to date.

I currently don't see how you'd keep a projection that reads multiple streams up to date unless you'd start including the version numbers in the query to LoadEvents. At that point, Change Feed feels like it's the only option, but sadly as you said it really needs a filtering option.

For example, let's say I have a shopping cart stream per user and I want to add an overview page for a service engineer across users that shows the total number of shopping carts that have items in them.

**Comment by jkonecki** [comment]
To be honest, Thomas, I don't use Eveneum in projections directly.

The goal for Eveneum is to be simple library for storing events - a
full-blown support for multi-stream projections would require a global
index or other complex indexing structure.

What I do, without major issues, is for projections to subscribe to
real-time events through a separate messaging mechanism: I use Microsoft
Orleans framework and utilize streams feature (essentially pub/sub). The
aggregate would persist event in CosmosDB using Eveneum and after
successful commit publish it to a certain topic for projections to
subscribe.

I only use Eveneum for projection rebuilding, where I load all events
(filtering on StreamId and BodyType to only load events that projection is
subscribed to). I would unsubscribe projection from topics, process stored
events and then resubscribe to process remaining events that were queued.

In my system I had the above infrastructure before I switched to Eveneum.
That's why I don't use ChangeFeed. If you're building something from
scratch I would definitely consider ChangeFeed - yes, you need to filter
events yourself and it would use few more RUs that you really need, but I
bet it would still be acceptable for you.

Nevertheless, I would be interested to know how you would like this
implemented within Eveneum!

I'm considering the idea of defining indexed streams, which would allow you
to create the definition of new streams that contain events from other
streams. This would effectively create a new stream in CosmosDB with
payload being just a pointer to the actual event in other stream. When
reading such a stream, Eveneum would read the events from other streams
based on the pointers for you. When storing events for the original stream,
Eveneum would append the pointer in any indexed stream based on your
definitions as well.

Each projection would have concrete, single stream to work with. I need to
consider if a single, 10GB partition would suffice or if I need to support
splitting single stream between multiple physical partitions.

**Comment by Mardallas** [comment]
> > Sorry for a late reply, didn't get a notification from GitHub.
> 
> > Eveneum would expose a `Serializer` class that would take documents returned from Change Feed and deserialize them to `EventData` or `Snapshot` objects. I don't think we need to make `EveneumDocument` public - as long as I can deserialize the raw document from Change Feed.
> 
> Yes, this sounds good to me! As long as there is a way to get IReadOnlyList without further hassle to EventData, I am fine. I actually did already my implementation, but I thinnk this is something that should be done in the library.
> 
> > Do you guys use ChangeFeedProcessor or SQL API?
> 
> I use Azure functions, where I get list of IReadOnlyList as an argument, when collection has a change.
> 
> -- ARi

@AriKuorikoski  -
Stumbled upon your request while trying to create projection.
I have a very similar requirement to what you stated and not sure if  such a library was created on Eveneum. 
Would it be possible for you to share code for deserialization (one that you implemented in 2019). 

Thank you in advance.

regards,
Mar
