### ISSUE TITLE
Should there be possibility to retrieve headers only?

### ISSUE THREAD

**Issue by Aakoo76** [Eveneum/Eveneum#7]
I wan't to have a fallback mechanism in place in my solution, where I could scheduled retrieve all stream headers that have been modified since the given time. This mechanism finds all changed headers from cosmos, and compares those to the read models metadata, where I store the stream id and stream version. if mismatch, then I would replay events on the given stream and update the read model to latest version.

In Cosmos there is the field _ts, which is the timestamp when document has been modified the last time. Could that be exposed somehow and be used here?

-- ARi

**Comment by jkonecki** [comment]
I don't know if using timestamp is the way to go - `_ts` field is supposed to be an internal CosmosDB implementation detail. I would suggest you use own field, which you can store as metadata.

Now, I wonder if you really need to load all modified streams and than keep reading individual streams. Would it be enough for you to just load all events created since a certain point in time?

If so, you can use IAdvancedEventStore.LoadEvents method - with the query:

`SELECT * FROM c WHERE c.Metadata.CreatedAt >= '<your timestamp>'`

The above assumes you store event creation time in `Metadata.CreatedAt` field.

Regardless of the above, the feature of being able to get stream headers for modified streams is interesting enough and I'll proceed to implement it.
